import { Geist, Geist_Mono } from "next/font/google";
import Navwrapper from "../Navwrapper";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NorthStaRs",
  description: "Generated by NorthStaRs app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* mujhe dikkat ho rahi thi issliye maine navbar ka component bana ke usko
        Navwrapper me daal diya aur usko yaha call kar ke children ko wrap kar diya hai kaam toh kar raha hai
         */}
        <Navwrapper>
        {children}
        </Navwrapper>
      </body>
    </html>
  );
}
